config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  
  resources :podcastscrappings do
    match '/scrape', to: 'podcastscrappings#scrape', via: :post, on: :collection
  end

  get '/index_user', to: 'user#index', as: 'user_index'
  get '/login_user', to: 'user#login', as: 'user_login'
  get '/logout_user', to: 'user#logout', as: 'user_logout'
  get '/create_user', to: 'user#create', as: 'create_user'
  get '/fail_user', to: 'user#fail', as: 'fail_user'
  get '/profile_user', to: 'user#profile', as: 'user_profile'
  get '/favorite', to: 'favorite#create', as: 'favorite_create'
  get '/favorite_destroy', to: 'favorite#destroy', as: 'favorite_destroy'
  get '/favorite_fail', to: 'favorite#fail', as: 'favorite_fail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/podcasts_spider.rb
class PodcastsSpider < Kimurai::Base

  @name = 'podcasts_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    podcastList = []
    response.css('div.span3').each do |podcastTitle|
      item = {}

      item[:title] = podcastTitle.css('strong.tit')&.text&.squish
      item[:image_url] = podcastTitle.css('img.lazyload').attr('data-src')&.text&.squish

      podcastList.append(item)
    end
    podcastList.pop
    podcastList.each do |podcast|
      Podcastscrapping.where(podcast).first_or_create
    end
  end
end

app/models/podcastscrapping.rb
class Podcastscrapping < ApplicationRecord
    has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :favorites, dependent: :destroy

    validates name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: { minimum: 3 }
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
    def index
    end

    def create
        redirect_to favorite_fail_path and return if Favorite.where(user_id:current_user.id, podcastscrapping_id:params[:podcastscrapping_id]).present?
        Favorite.create(user_id:current_user.id, podcastscrapping_id:params[:podcastscrapping_id])
        redirect_to root_path and return
    end

    def destroy
        Favorite.where(user_id:current_user.id, podcastscrapping_id:params[:podcastscrapping_id]).first.destroy
        redirect_to user_profile_path and return
    end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @podcastscrappings = Podcastscrapping.all
  end
end

app/controllers/podcastscrappings_controller.rb
class PodcastscrappingsController < ApplicationController
  before_action :set_podcastscrapping, only: %i[ show edit update destroy ]

  def index
  end

  def scrape
    url = 'https://www.podbean.com/science-podcasts'
    response = PodcastsSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
    redirect_to root_path and return
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcastscrapping
      @podcastscrapping = Podcastscrapping.find(params[:id])
    end

    def podcastscrapping_params
      params.require(:podcastscrapping).permit(:title)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
    end

    def create
        if params[:commit] == "Login"
            @user = User.find_by(email:params[:email])
            if @user && @user.authenticate(params[:password_digest]) 
                sign_in(@user)
                redirect_to root_path and return
            else
                redirect_to fail_user_path and return
            end
        end
        
        if User.find_by(email:params[:email]).present?
            redirect_to fail_user_path and return
        else
            @user = User.new
            @user.name = params[:name]
            @user.email = params[:email]
            @user.password = params[:password_digest]
            @user.admin_user = false
            @user.save!
            # sign_in(@user)
            redirect_to root_path and return
        end
    end
    
    def fail
    end

    def logout
        sign_out
        redirect_to root_path and return
    end

    def profile
        @user = current_user
    end
end
  

app/helpers/favorites_queries.rb
module FavoritesQueries
    def favorite(podcastscrapping_id)
        Favorite.where(user_id:current_user.id, podcastscrapping_id:podcastscrapping_id).empty?
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def no_favorite(podcastscrapping_id)
        Favorite.where(user_id:current_user.id, podcastscrapping_id:podcastscrapping_id).empty?
    end

    def can_desfavorite?(podcastscrapping_id)
        current_user && no_favorite(podcastscrapping_id)
    end

    def can_favorite?(podcastscrapping_id)
        current_user && no_favorite(podcastscrapping_id)
    end

    def block_access
        if current_user.present?
            redirect_to root_path
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/views/favorite/fail.html.erb
<p style="color: green"><%= notice %></p>

<div>
    <p>Podcast already added</p>
  <%= link_to "Back to home", root_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Home</h1>

<%= button_to 'Scrape', scrape_podcastscrappings_path %>
<%= link_to "Create user", user_index_path unless current_user %>
<%= link_to "Login", user_login_path unless current_user %>
<%= link_to "Profile", user_profile_path if current_user %>
<%= link_to "Logout", user_logout_path if current_user %>

<div id="podcastscrappings">
  <% @podcastscrappings.each do |podcastscrapping| %>
    <%= render podcastscrapping %>
    <p>
      <%= link_to "Show this podcast", podcastscrapping %>
    </p>
  <% end %>
</div>

app/views/podcastscrappings/_podcastscrapping.html.erb
<div id="<%= dom_id podcastscrapping %>">
  <p>
    <strong>Title:</strong>
    <%= podcastscrapping.title %>
    <%= link_to "Favoritar", favorite_create_path(@no_favorite, :podcastscrapping_id => podcastscrapping.id) if can_favorite?(podcastscrapping.id) %>
    <%= link_to "Desfavoritar", favorite_destroy_path(@destroy, :podcastscrapping_id => podcastscrapping.id) unless can_desfavorite?(podcastscrapping.id) %>

  </p>

  <p>
    <img src="<%= podcastscrapping.image_url %>"/>
  </p>

</div>

app/views/podcastscrappings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @podcastscrapping %>

<div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/user/create.html.erb
<p style="color: green"><%= notice %></p>

<div>
    <p> User created</p>
  <%= link_to "Back to home", root_path %>
</div>

app/views/user/fail.html.erb
<p style="color: green"><%= notice %></p>

<div>
    <p>Fail to login</p>
  <%= link_to "Back to home", root_path %>
</div>

app/views/user/index.html.erb
<%= form_with url: create_user_path , method: :get do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :email%>
    <%= f.text_field :email%>

    <%= f.label :password%>
    <%= f.password_field :password_digest%>

    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation%>

    <%= f.submit "Create"%>
<% end %>

app/views/user/login.html.erb
<%= form_with url: create_user_path , method: :get do |f| %>
    <%= f.label :email%>
    <%= f.text_field :email%>

    <%= f.label :password%>
    <%= f.password_field :password_digest%>

    <%= f.submit "Login"%>
<% end %>

app/views/user/logout.html.erb
<p style="color: green"><%= notice %></p>

<div>
    <p>Logout</p>
  <%= link_to "Back to home", root_path %>
</div>

app/views/user/profile.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profile</h1>
<p> Nome: <%= @user.name %></p>
<p> Email: <%= @user.email %></p>

<p> Editar: adicionar botao para editar perfil</p>

<p> Favoritos:</p>
<div id="favorites">
  <% current_user.favorites.each do |favorite_podcast| %>
    <div>
    <p>
        <%= Podcastscrapping.find_by(id:favorite_podcast.podcastscrapping_id).title %>
      <%= link_to "Desfavoritar", favorite_destroy_path(@destroy, :podcastscrapping_id => favorite_podcast.podcastscrapping_id) unless can_desfavorite?(favorite_podcast.podcastscrapping_id) %>

    </p>
    <p>
        <img src="<%= Podcastscrapping.find_by(id:favorite_podcast.podcastscrapping_id).image_url %>"/>
    </p>
    </div>
  <% end %>
</div>

<%= link_to "Back to home", root_path %>
<%= link_to "Logout", user_logout_path if current_user %>

app/views/users/index.html.erb
<%= form_with url: create_user_path , method: :get do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :email%>
    <%= f.text_field :email%>

    <%= f.label :password%>
    <%= f.password_field :password_digest%>

    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation%>

    <%= f.submit "create"%>
<% end %>